In [2]:
import numpy as np

In [3]:
vec = np.array([1,2,3,4,np.nan,6,7,8])

In [5]:
np.maximum.accumulate(vec )

array([  1.,   2.,   3.,   4.,  nan,  nan,  nan,  nan])

In [6]:
np.fmax.accumulate(vec )

array([ 1.,  2.,  3.,  4.,  4.,  6.,  7.,  8.])

In [9]:
np.where(np.isnan(vec), np.nan, np.fmax.accumulate(vec))

array([  1.,   2.,   3.,   4.,  nan,   6.,   7.,   8.])

In [10]:
np.isinf(vec)

array([False, False, False, False, False, False, False, False], dtype=bool)

In [12]:
np.nanargmax(vec)

7