In [1]:
import pandas as pd
import numpy as np
%load_ext Cython

## python version

In [2]:
%quickref

In [3]:
%%time
def int_isnan(x):
    return np.isnan(float(x))

def do_neutral(alpha,ind):
    vcrst = np.full_like(alpha,fill_value=np.nan)# maybe slow down
    ind_sum = dict()
    ind_num = dict()
    for kk in range(len(alpha)):
        v = alpha[kk]
        g = ind[kk]
        if not np.isinf(v) and not np.isnan(v) and not int_isnan(g) and g>=0: #TODO test nan ind and minus ind value
            if g not in ind_sum.keys():
                ind_sum[g] = v
                ind_num[g] = 1
            else:
                ind_sum[g] += v
                ind_num[g] += 1
    for g in ind_sum.keys():
        ind_sum[g] /= ind_num[g]
        
    for kk in range(len(alpha)):
        if not np.isinf(alpha[kk]) and not np.isnan(alpha[kk]) and not int_isnan(ind[kk]) and ind[kk]>=0: #TODO g is large minus number
            vcrst[kk] = alpha[kk] - ind_sum[ind[kk]]
        else:
            vcrst[kk] = np.nan
    return vcrst
            
            
def neutral(array, industry,market=False):
    aaret = np.full_like(array,fill_value=np.nan)
    if market == True:
        for di in range(array.shape[0]):
            aaret[di,:] = array[di, :] - array[np.where(~np.isnan(array[di, :])),:].mean()
    else:
        for di in range(array.shape[0]):
            aaret[di,:] = do_neutral(array[di, :], industry[di, :])
    return aaret

alpha = np.random.randn(2500,2500)
ind = np.random.randint(25, size=(2500, 2500))
neutral(alpha,ind,market=False)

CPU times: user 45.8 s, sys: 424 ms, total: 46.2 s
Wall time: 46.1 s


## pandas version

In [73]:
%%time
def industry_neutral(df_signal,df_ind):
    industry_ids = pd.unique(pd.Series(df_ind.values.ravel()).dropna())
    industry_ids.sort()
    l = []
    for industry_id  in industry_ids:
        df_industry_one = df_ind == industry_id
        df_industry_one = df_industry_one.replace(False,np.nan)
        df_signal_one_indstry = df_industry_one * df_signal
        sr_signal_sum_one_indstry = df_signal_one_indstry.mean(1)
        df_signal_one_indstry_neutral = df_signal_one_indstry.sub(sr_signal_sum_one_indstry.values,axis=0)
        l.append(df_signal_one_indstry_neutral.fillna(0))
    return sum(l)
df_alpha = pd.DataFrame(np.random.randn(2500,2500))
df_ind = pd.DataFrame(np.random.randint(25, size=(2500, 2500)) )
df1 = industry_neutral(df_alpha,df_ind)

CPU times: user 20.8 s, sys: 17.5 s, total: 38.3 s
Wall time: 22.4 s


## pandas-numpy version2

In [68]:
%%time
def industry_neutral(df_signal,df_ind):
    df_ind = df_ind.astype('float32').values
    df_signal = df_signal.values
    industry_ids = pd.unique(pd.Series(df_ind.ravel()).dropna())
    industry_ids.sort()
    l = []
    for industry_id  in industry_ids:
#         df_industry_one = df_ind == industry_id
#         df_industry_one = df_industry_one.astype('float32').replace(False,np.nan)
        np.place(df_ind,df_ind == industry_id,[np.nan])
        df_signal_one_indstry = df_ind * df_signal
        sr_signal_sum_one_indstry = np.nanmean(df_signal_one_indstry,1)
        df_signal_one_indstry_neutral = df_signal_one_indstry - sr_signal_sum_one_indstry
        l.append(np.nan_to_num(df_signal_one_indstry_neutral ))
    return sum(l)


df2 = industry_neutral(df_alpha,df_ind)

CPU times: user 10.8 s, sys: 8.77 s, total: 19.5 s
Wall time: 19.5 s


In [70]:
(df1.values == df2).all()

False

In [71]:
df1

0         1         2         3         4         5         6     \
0    -0.138938  0.466766 -0.315825  1.880030 -1.173142  1.409573  0.012022   
1     0.233981 -1.169011 -0.393371 -1.093623 -0.434953  1.103897 -0.221288   
2    -0.539499  0.445228  1.827668 -1.530336  1.531208 -1.254695 -0.478856   
3    -1.364940  0.535926  1.782628 -1.562931  0.066462  0.503770 -0.660225   
4    -1.141802 -0.241081 -0.759809 -1.046608 -0.562807 -0.604013  0.301110   
5    -1.184308  0.429968 -0.014340  0.382282 -0.463205 -1.139052 -0.025755   
6     1.582791 -0.301220 -0.721126 -0.447929 -1.198409  0.111634  1.698394   
7     2.004075  0.554375 -0.153361 -1.555681 -0.649636  0.058392  1.816617   
8     0.313119  0.650086 -0.311688  0.056528  0.523877  0.683543  1.366957   
9     0.822539 -0.057481  0.632807 -0.270442 -0.158030  1.065352  0.079561   
10   -0.380147 -0.535990 -1.364659  0.560605  0.368054  1.852475 -2.391757   
11   -0.605439  2.232055  0.366357 -0.218044 -0.329300  0.208940  0.172593   
12   -0.330621 -1.501933  0.494987 -1.153172 -0.520809  1.505644  0.168141   
13    0.325145  0.505338 -1.172530  1.208993  0.852227 -0.379487  1.489647   
14   -1.791140 -0.573286  1.323700  0.717429  0.989080  1.077597  0.063377   
15    0.001833  0.115321  2.689469  0.095852 -0.019533  1.262791 -1.065812   
16    0.160652  0.213072  0.969665  0.656757 -0.074152 -0.915760 -0.625923   
17   -1.053461  0.668885  0.268076 -1.237481  1.470772  0.185179 -2.225972   
18   -0.101299 -0.765813  0.522693 -1.453509 -1.200221  1.097466 -0.454115   
19    1.835514 -0.077209  0.493903  0.680064 -0.587006 -0.931086  1.068836   
20   -0.686216  0.174656  1.123449 -0.265250  0.530306 -0.690568 -1.055246   
21    0.377179 -1.157768 -0.353006  0.370740 -0.878745  0.112098 -1.068302   
22    0.595090  0.220004 -0.914045  0.768059  1.548383  0.675467  0.786263   
23    0.634765  0.267988 -1.360583 -0.576818  1.037233  1.281743 -0.630612   
24   -0.217285  0.974079 -0.089439  0.790397  0.132995  1.042359  0.763364   
25   -0.778433  0.238404  0.422995 -0.883889 -0.691445 -0.028800 -1.932938   
26    1.308633  1.074179  1.811212  1.319992 -0.688098 -1.782010 -2.439801   
27   -1.220536  0.424311  0.948324 -0.781097  0.341407 -0.066939 -1.808262   
28   -0.830438  0.060347 -0.116937  1.601038 -0.385794 -0.467203 -0.473437   
29    0.708337  0.293576 -0.872245 -0.817585 -0.463885  0.485883  0.759702   
...        ...       ...       ...       ...       ...       ...       ...   
2470  0.965414  0.144818  1.061662 -0.836736 -0.500157  0.184692 -0.570743   
2471  0.655506  0.356773 -0.063983 -0.887003 -0.238508 -0.152890  0.946695   
2472  0.242579  1.370171 -0.758847 -0.497188  1.344457  0.577544 -0.578863   
2473 -0.574430 -0.425675  0.317086  0.405967  0.188103 -0.086063  0.116274   
2474  0.035781  0.829133 -0.113798 -0.589363 -0.665250  0.878084 -0.374411   
2475  1.996165 -0.229859  0.212667  0.464176 -0.495738  0.927932 -0.453493   
2476  0.929028 -1.274538  1.648056  1.673320  1.694510 -1.197190  1.840304   
2477 -0.826011 -0.835484  0.713738 -2.493589 -0.546937  0.722817  0.826374   
2478 -1.466593  1.618787 -0.092427  0.449297 -1.154757 -0.003641 -0.299682   
2479 -2.102969  1.237496  1.235998  0.361419  0.105417  2.269599  0.581952   
2480  0.404728  2.403408  1.462061  1.220884 -1.263182 -0.977079 -0.775480   
2481 -1.017616  0.207813  0.452060  0.498413  0.155028  0.092705 -1.018859   
2482  0.806169 -2.466651 -0.945513  0.256263  1.143503 -0.814017 -1.223026   
2483  0.094407  1.877729  1.181389  0.181278  0.353794 -1.612894 -1.995502   
2484  0.514014  0.989743  0.897671  0.530909 -0.933844 -0.170724  1.010714   
2485  0.653323  0.299602  0.659728 -0.009320 -0.341462 -0.643171  0.942681   
2486 -0.669628 -0.066710  0.653946 -1.347954 -1.942733 -0.920823  0.130521   
2487  0.856538  0.356575 -0.954301 -1.650950  0.863762  1.840202  0.287532   
2488 -0.087018 -1.250617  0.116077  1.096588 -1.735863 -0.281267 -0.249581   
2489  0.724208 -0.783902  0.0685

In [72]:
df2

array([[  1.42582618e+02,  -8.25694641e-01,  -1.25799873e+02, ...,
          5.14848669e+01,   1.45628973e+02,  -1.16993664e+02],
       [ -1.08961429e+02,   5.77605188e+02,  -2.25654620e+00, ...,
          3.39126791e+01,  -1.54613607e+02,  -2.76855676e-01],
       [ -5.38085092e+02,   3.33183785e+01,   9.17606652e+00, ...,
         -1.83648917e+01,  -1.24243599e+02,  -1.62112671e+02],
       ..., 
       [  3.48403014e+02,   1.64090218e+01,   0.00000000e+00, ...,
          5.25159992e+02,   1.35720698e+03,  -2.00376544e+02],
       [  0.00000000e+00,   4.32565750e+02,  -3.40533686e+02, ...,
          1.05542662e+01,   1.64389442e+00,  -3.17759832e+02],
       [  7.10261809e+01,  -2.88617847e+00,   6.99359332e+02, ...,
         -9.33400423e+01,   6.91050767e+00,  -9.08673573e+01]])

In [60]:
df_alpha = pd.DataFrame(np.random.randn(2500,2500))
df_ind = pd.DataFrame(np.random.randint(25, size=(2500, 2500)) )
 

df_ind = df_ind.astype('float32').values
df_signal = df_alpha.values
industry_ids = pd.unique(pd.Series(df_ind.ravel()).dropna())
industry_ids.sort()

l = []
for industry_id  in industry_ids:
#         df_industry_one = df_ind == industry_id
#         df_industry_one = df_industry_one.astype('float32').replace(False,np.nan)
    np.place(df_ind,df_ind == industry_id,[np.nan])
    df_industry_one = df_ind
    df_signal_one_indstry = df_industry_one * df_signal
    sr_signal_sum_one_indstry = np.nanmean(df_signal_one_indstry,1)
    df_signal_one_indstry_neutral = df_signal_one_indstry - sr_signal_sum_one_indstry
    l.append(np.nan_to_num(df_signal_one_indstry_neutral ))
sum(l)

array([[ -1.52194445e+02,   0.00000000e+00,  -1.93285192e+00, ...,
         -8.72563052e+01,  -4.98352626e+01,   4.05530809e+01],
       [ -8.51405650e+01,  -5.43561921e+02,  -3.84196762e+02, ...,
          6.60477456e+01,  -2.68277032e+01,   7.78027548e+01],
       [ -2.34502493e+02,  -6.12947885e+02,  -1.21603825e+01, ...,
         -7.49301117e+02,  -6.55310608e-01,   7.71821737e+02],
       ..., 
       [  1.57770690e+01,  -1.83423198e+02,   2.66597026e+01, ...,
          7.32081209e+02,  -1.98639661e+01,   1.41731879e+03],
       [ -2.34206300e+02,   2.45571872e+02,   1.91831496e+02, ...,
         -1.69791136e+00,  -4.00176920e+02,   3.85673424e+01],
       [  8.26688872e+00,  -1.41184263e+01,  -5.06768331e+00, ...,
         -5.70372228e-01,   0.00000000e+00,  -2.55615093e+02]])

AttributeError: 'numpy.ndarray' object has no attribute 'nanmax'

In [39]:
df_ind


array([[24,  2, 24, ..., 16, 10, 11],
       [ 0, 23, 13, ..., 24,  9, 19],
       [ 4, 21, 14, ..., 18,  7, 10],
       ..., 
       [12, 23, 14, ...,  2, 15,  0],
       [20, 15, 17, ...,  6, 24,  6],
       [16,  0,  8, ...,  7, 21,  7]])

## use cython

In [9]:
%%time
%%cython -a
import numpy as np
cimport numpy as np
cimport cython
cdef extern from "math.h":
    int isnan(double x)
    

cdef int_isnan(int x):
    return isnan(float(x))
    
DTYPE = np.float32
ctypedef np.float32_t DTYPE_T 
ctypedef np.int32_t INDTYPE_T 



cdef do_neutral(np.ndarray[np.float32_t] alpha,np.ndarray[np.int32_t] ind):
    cdef int kk, jj
    cdef DTYPE_T v
    cdef INDTYPE_T g 
    cdef dict ind_sum = dict()
    cdef dict ind_num = dict()
    
    cdef np.ndarray[np.float32_t] vcrst = np.full_like(alpha,fill_value=np.nan,dtype=np.float32)# maybe slow down
    
#     ind_sum = dict()
#     ind_num = dict()
    for kk in xrange(len(alpha)):
        v = alpha[kk]
        g = ind[kk]
        if not np.isinf(v) and not np.isnan(v) and not int_isnan(g) and g>=0: #TODO test nan ind and minus ind value
            if g not in ind_sum.keys():
                ind_sum[g] = v
                ind_num[g] = 1
            else:
                ind_sum[g] += v
                ind_num[g] += 1
    for g in ind_sum.keys():
        ind_sum[g] /= ind_num[g]
        
    for kk in xrange(len(alpha)):
        if not np.isinf(alpha[kk]) and not np.isnan(alpha[kk]) and not int_isnan(ind[kk]) and ind[kk]>=0: #TODO g is large minus number
            vcrst[kk] = alpha[kk] - ind_sum[ind[kk]]
        else:
            vcrst[kk] = np.nan
    return vcrst
            
            
cdef neutral(np.ndarray[np.float32_t,ndim=2] array, np.ndarray[np.int32_t,ndim=2] industry,market=False):
    cdef np.ndarray[np.float32_t,ndim=2] aaret = np.full_like(array,fill_value=np.nan,dtype=np.float32)
    cdef int di
    if market == True:
        for di in xrange(array.shape[0]):
            aaret[di,:] = array[di, :] - array[np.where(~np.isnan(array[di, :])),:].mean()
    else:
        for di in xrange(array.shape[0]):
            aaret[di,:] = do_neutral(array[di, :], industry[di, :])
    return aaret

cdef main():
    cdef np.ndarray[np.float32_t,ndim=2] alpha = np.random.randn(2500,2500).astype(np.float32)
    cdef np.ndarray[np.int32_t,ndim=2] ind = np.random.randint(25, size=(2500, 2500),dtype=np.int32)
    neutral(alpha,ind,market=False)
    
main()

CPU times: user 23 s, sys: 232 ms, total: 23.3 s
Wall time: 25.1 s


## weave inline

In [ ]:
%%cython
import numpy as np
cimport numpy as np
cpdef foo(n):
    cdef np.ndarray[double] vola = np.empty(n, dtype=float)
    return vola

foo(4)

## pandas multiindex version

In [34]:
%%time
def industry_neutral(df_signal,df_ind):
    df_sig = pd.DataFrame(df_signal.unstack(),columns=['sig'])
    sr_ind = df_ind.unstack()
    df_sig['ind'] = sr_ind
    df_sig['sig_indmean']=df_sig.groupby(level=0).transform('mean')
    sr = df_sig['sig'] - df_sig['sig_indmean']
    return sr.unstack()
df_alpha = pd.DataFrame(np.random.randn(2500,2500))
df_ind = pd.DataFrame(np.random.randint(25, size=(2500, 2500)) )
df = industry_neutral(df_alpha,df_ind)

ValueError: Wrong number of items passed 2, placement implies 1