In [2]:
import numpy as np

In [14]:
array = np.array([[4,2,7,1],[4,3,2,1],[1,3,7,5]],dtype='float32')
array[1,1] = np.nan
array[1,2] = np.nan
print array


[[  4.   2.   7.   1.]
 [  4.  nan  nan   1.]
 [  1.   3.   7.   5.]]


In [15]:
order = array.argsort()
print order

[[3 1 0 2]
 [3 0 1 2]
 [0 1 3 2]]


In [10]:
ranks = order.argsort()
print ranks

[[2 1 3 0]
 [3 2 1 0]
 [0 1 3 2]]


In [17]:
def rank(arr):
    order = array.argsort()
    ranks = order.argsort()
    return ranks

In [18]:
rank(array)

array([[2, 1, 3, 0],
       [1, 2, 3, 0],
       [0, 1, 3, 2]])

In [4]:
from scipy.stats import  rankdata
rankdata(np.array([4,2,7,1])[-1])

array([ 1.])