In [17]:
import numpy as np
import scipy.stats
import pdb
import pandas as pd
from functools import  partial

In [105]:
def qcut(arr,quantile = [0,20,40,60,80,100]):
    
    if len(arr.shape) == 2:
        rownum = arr.shape[0]
        arr_ret = np.full_like(arr,fill_value=np.nan)
        for rn in range(rownum):
            vec = arr[rn]
            vec_not_nan = ~np.isnan(vec)
            if not  vec_not_nan.any():
                break
#             vec[vec_not_nan] = scipy.stats.rankdata(vec[vec_not_nan] , method='average')
            vec_denan = vec[vec_not_nan]
            quantiles = np.percentile(vec_denan,quantile)
#             arr_ret[rn,vec_not_nan] = np.digitize(vec_denan,quantiles,right = True)
#             print vec[vec_not_nan]
#             print quantiles
            for i,v1 in enumerate(quantiles):
                if i >= len(quantile)-1:
                    break
                
                v2 = quantiles[i+1]
                if i+1 == len(quantiles) -1:
                    vec_bool_one_quantile = (vec >= v1) & (vec <= v2)
                else:
                    vec_bool_one_quantile = (vec >= v1) & (vec < v2)
                
                arr_ret[rn,vec_bool_one_quantile] = i+1
        return arr_ret
            
    elif len(arr.shape) == 1:
        rownum = arr.shape[0]
        arr_ret = np.full_like(arr,fill_value=np.nan)
        for rn in range(rownum):
            vec = arr 
            vec_not_nan = ~np.isnan(vec)
            if not  vec_not_nan.any():
                break
            vec_denan = vec[vec_not_nan]
            quantiles = np.percentile(vec_denan,quantile)
#             arr_ret[rn,vec_not_nan] = np.digitize(vec_denan,quantiles)
#             print 'quantiles',quantiles
            for i,v1 in enumerate(quantiles):
                    if i >= len(quantile)-1:
                        break

                    v2 = quantiles[i+1]
                    if i+1 == len(quantiles) -1:
                        vec_bool_one_quantile = (vec >= v1) & (vec <= v2)
                    else:
                        vec_bool_one_quantile = (vec >= v1) & (vec < v2)

                    arr_ret[vec_bool_one_quantile] = i+1
            return arr_ret
        
        
    
#     np.percentile(arr[~np.isnan(arr)],50)
    


In [112]:
arr = np.array([[1,2,2,np.nan,3,4,5],[1,2,3,np.nan,3,4,5],[1,2,999,np.nan,3,4,5],[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]])
print arr
qcut(arr)

[[   1.    2.    2.   nan    3.    4.    5.]
 [   1.    2.    3.   nan    3.    4.    5.]
 [   1.    2.  999.   nan    3.    4.    5.]
 [  nan   nan   nan   nan   nan   nan   nan]]


C:\Users\Administrator\Anaconda2\lib\site-packages\ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in greater_equal
C:\Users\Administrator\Anaconda2\lib\site-packages\ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in less
C:\Users\Administrator\Anaconda2\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in greater_equal
C:\Users\Administrator\Anaconda2\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in less_equal


array([[  1.,   3.,   3.,  nan,   4.,   5.,   5.],
       [  1.,   2.,   4.,  nan,   4.,   5.,   5.],
       [  1.,   2.,   5.,  nan,   3.,   4.,   5.],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan]])

In [107]:
arr = np.array([[1,5,5,5,5,5,5,5,5,5]])
print arr
qcut(arr)

[[1 5 5 5 5 5 5 5 5 5]]


array([[1, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [108]:
arr = np.array([1,1,1,1,1,1,5])
print arr
qcut(arr)

[1 1 1 1 1 1 5]


array([5, 5, 5, 5, 5, 5, 5])

In [24]:
arr = np.array([[1,2,3,np.nan,4,5,6],[1,2,3,np.nan,4,5,7]])
df = pd.DataFrame(arr)
print df
func = partial(pd.qcut,q= 5  ,retbins =False)
df.apply(func,axis=1)

     0    1    2   3    4    5    6
0  1.0  2.0  3.0 NaN  4.0  5.0  6.0
1  1.0  2.0  3.0 NaN  4.0  5.0  7.0


0       1       2   3       4       5       6
0  [1, 2]  [1, 2]  (2, 3] NaN  (3, 4]  (4, 5]  (5, 6]
1  [1, 2]  [1, 2]  (2, 3] NaN  (3, 4]  (4, 5]  (5, 7]

In [34]:
np.percentile(arr[~np.isnan(arr)],[0,20,50,75,100])

array([ 1.  ,  2.  ,  2.5 ,  3.75,  5.  ])

In [38]:
ar = np.array([1,2,2,np.nan,3,4,5])
scipy.stats.rankdata(ar, method='ordinal')

array([1, 2, 3, 7, 4, 5, 6], dtype=int64)